### PR TITLE
R resources

### PR DESCRIPTION
**Pull request by mrjoh3**
I have added a page of web based R resources. For each resource a preview card is generated based on available metadata (similar to a slack preview). The resources list is maintained in an included CSV.

All resources are split into categories such as:
* books
* blogs
* videos
* course materials
* other resource lists

The page includes a section with a searchable table to make it easier to find resources and a section describing how others can add to the list.

This PR just includes the rmd file, CSV file and the site yaml there. As are no GH actions setup for the site, I think it will be easiest to rebuild the site once the PR is approved.

### CODE REVIEW

**Comment by wfmackey** [comment]
this looks cool as, @mrjoh3 !

**Review by MattCowgill — APPROVED** [review]
This is great! I wonder whether it would be worth adding an introductory sentence or two at the top, and maybe also pointing brand-new users to the best place to start (R4DS?)? But as-is I think this is great and should get added to the main site

**Comment by MattCowgill** [comment]
Should I merge?

**Comment by mrjoh3** [comment]
I will just rebuild the site in master and push if successful

**Comment by mrjoh3** [comment]
all done, the site built without issue and is now live, I will add something to the Slack Channel later this afternoon

**Pull request merged**
